package com.menethil.tinymall.db.dao;

import com.menethil.tinymall.db.domain.TinymallUser;
import com.menethil.tinymall.db.domain.TinymallUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    long countByExample(TinymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int insert(TinymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int insertSelective(TinymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallUser selectOneByExample(TinymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallUser selectOneByExampleSelective(@Param("example") TinymallUserExample example, @Param("selective") TinymallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TinymallUser> selectByExampleSelective(@Param("example") TinymallUserExample example, @Param("selective") TinymallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    List<TinymallUser> selectByExample(TinymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    TinymallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallUser record, @Param("example") TinymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallUser record, @Param("example") TinymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TinymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}