package com.menethil.tinymall.db.dao;

import com.menethil.tinymall.db.domain.TinymallComment;
import com.menethil.tinymall.db.domain.TinymallCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    long countByExample(TinymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int insert(TinymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int insertSelective(TinymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallComment selectOneByExample(TinymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallComment selectOneByExampleSelective(@Param("example") TinymallCommentExample example, @Param("selective") TinymallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TinymallComment> selectByExampleSelective(@Param("example") TinymallCommentExample example, @Param("selective") TinymallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    List<TinymallComment> selectByExample(TinymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    TinymallComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallComment record, @Param("example") TinymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallComment record, @Param("example") TinymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TinymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}