package com.menethil.tinymall.db.dao;

import com.menethil.tinymall.db.domain.TinymallStorage;
import com.menethil.tinymall.db.domain.TinymallStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    long countByExample(TinymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int insert(TinymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int insertSelective(TinymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallStorage selectOneByExample(TinymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallStorage selectOneByExampleSelective(@Param("example") TinymallStorageExample example, @Param("selective") TinymallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TinymallStorage> selectByExampleSelective(@Param("example") TinymallStorageExample example, @Param("selective") TinymallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    List<TinymallStorage> selectByExample(TinymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    TinymallStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallStorage record, @Param("example") TinymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallStorage record, @Param("example") TinymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TinymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}