package com.menethil.tinymall.db.dao;

import com.menethil.tinymall.db.domain.TinymallAddress;
import com.menethil.tinymall.db.domain.TinymallAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    long countByExample(TinymallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int insert(TinymallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int insertSelective(TinymallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallAddress selectOneByExample(TinymallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallAddress selectOneByExampleSelective(@Param("example") TinymallAddressExample example, @Param("selective") TinymallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TinymallAddress> selectByExampleSelective(@Param("example") TinymallAddressExample example, @Param("selective") TinymallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    List<TinymallAddress> selectByExample(TinymallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    TinymallAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TinymallAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallAddress record, @Param("example") TinymallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallAddress record, @Param("example") TinymallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TinymallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}